language: php
sudo: false
dist: trusty

services:
  - docker

addons:
  chrome: stable
  firefox: latest

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="chrome"
    - DRIVER_OPTIONS='{"args":["headless", "no-sandbox","window-size=1024,768"]}'
    - CHROMEDRIVER_VERSION="2.38"
    - START_XVFB="0"
    - SELENIUM_DRIVER=""

cache:
  directories:
    - $HOME/.composer/cache/files
    - jar

matrix:
  include:
    - php: 7.0
      env:
        - SELENIUM_DRIVER="2.53.1"
        - BROWSER_NAME="firefox"
    # XVFB with regular Chrome (not headless)
    - php: 7.2
      env:
        - DRIVER_OPTIONS='{"args":["no-sandbox","window-size=1024,768"]}'
        - START_XVFB=1
    # build with lowest deps
    - php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-lowest"
    # build with latest chromedriver
    - php: 7.2
      env:
        - CHROMEDRIVER_VERSION="latest"
    # build with latest geckodriver
    - php: 7.2
      env:
        - GECKODRIVER_VERSION="latest"

install:
  - travis_retry composer update --no-interaction $COMPOSER_FLAGS

before_script:
  - ./.build/before_script.sh

script:
  - ./vendor/bin/simple-phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - if [ -f ./logs/webdriver.log ]; then cat ./logs/webdriver.log; fi
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/mink-test-server.log ]; then cat ./logs/mink-test-server.log; fi
