on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DRIVER_URL: "http://localhost:4444"
  WEB_FIXTURES_HOST: "http://localhost:8002"

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.0]
        browser: [ chrome, firefox ]
        experimental: [false]
        os: ['ubuntu-latest']
        include:
          - { browser: 'safari', os: 'macos-latest', experimental: true }

    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.12.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: zip, :xdebug
          tools: composer

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: Install xvfb
        if: ${{ matrix.os != 'safari' }}
        run: |
          echo "::group::apt-get install"
          sudo apt-get install xvfb
          echo "::endgroup::"

      - name: Install dependencies
        run: |
          echo "::group::composer update"
          composer update --no-interaction --prefer-dist
          echo "::endgroup::"

          echo "::group::composer require symfony/phpunit-bridge"
          composer require symfony/phpunit-bridge
          echo "::endgroup::"

      - name: Start ChromeDriver
        if: ${{ matrix.browser == 'chrome' }}
        run: |
          google-chrome --version
          xvfb-run --server-args="-screen 0, 1280x720x24" --auto-servernum $CHROMEWEBDRIVER/chromedriver --port=4444 --verbose --whitelisted-ips=  &> ./logs/webdriver.log &

      - name: Start GeckoDriver
        if: ${{ matrix.browser == 'firefox' }}
        run: |
          firefox --version
          geckodriver --version
          xvfb-run --server-args="-screen 0, 1280x720x24" --auto-servernum $GECKOWEBDRIVER/geckodriver --host 127.0.0.1 -vv --port 4444 &>./logs/webdriver.log &

      - name: Start SafariDriver
        if: ${{ matrix.browser == 'safari' }}
        run: |
          defaults read /Applications/Safari.app/Contents/Info CFBundleShortVersionString
          xvfb-run --server-args="-screen 0, 1280x720x24" --auto-servernum /usr/bin/safaridriver -p 4444 --diagnose &>./logs/webdriver.log &

      - name: Start webserver
        shell: bash
        run: |
          export USE_ZEND_ALLOC=0
          mkdir -p ./logs
          php -S localhost:8002 -t ./vendor/mink/driver-testsuite/web-fixtures &> ./logs/mink-test-server.log &

      - name: Wait for browser & PHP to start
        run: |
          while ! nc -z localhost 4444 </dev/null; do echo Waiting for remote driver to start...; sleep 1; done
          while ! nc -z localhost 8002 </dev/null; do echo Waiting for PHP server to start...; sleep 1; done

      - name: Run tests
        env:
          BROWSER_NAME: ${{ matrix.browser }}
        run: |
          ./vendor/bin/phpunit -v

      - name: Archive logs artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs_browser-${{ matrix.browser }}_php-${{ matrix.php }}
          path: |
            logs
