on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DRIVER_URL: "http://localhost:4444"
  WEB_FIXTURES_HOST: "http://localhost:8002"

defaults:
  run:
    shell: bash

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-latest
        php: [ 7.4, 8.0, 8.1 ]
        browser: [ chrome, firefox ]
        experimental: [false]
        include:
          - php: 8.1
            experimental: true
            browser: chrome
            os: macos-latest
          - php: 8.1
            experimental: true
            browser: firefox
          - php: 8.1
            experimental: true
            browser: safari
            os: macos-latest
          - php: 8.2
            experimental: true
            browser: chrome
            os: ubuntu-latest
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: zip, :xdebug
          tools: composer

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: ${{ matrix.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "::group::apt-get install"
            sudo apt-get install xvfb
            echo "::endgroup::"
          fi;

          echo "::group::composer update"
          composer update --no-interaction --prefer-dist
          echo "::endgroup::"

          echo "::group::composer require symfony/phpunit-bridge"
          composer require symfony/phpunit-bridge
          echo "::endgroup::"

      - name: Start webdriver
        shell: bash
        run: |
          set -ex
          mkdir -p ./logs
          XVFB=""
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            XVFB="xvfb-run --auto-servernum"
          fi;

          if [[ "${{ matrix.browser }}" == "chrome" ]]; then
            $XVFB $CHROMEWEBDRIVER/chromedriver --port=4444 --verbose --whitelisted-ips=  &> ./logs/webdriver.log &
          else
            $XVFB $GECKOWEBDRIVER/geckodriver --host 127.0.0.1 -vv --port 4444 &>./logs/webdriver.log &
          fi;
          
          while ! nc -z localhost 4444 </dev/null; do echo Waiting for driver to start...; sleep 1; done

      - name: Start webserver
        shell: bash
        run: |
          export USE_ZEND_ALLOC=0
          mkdir -p ./logs
          php -S localhost:8002 -t ./vendor/mink/driver-testsuite/web-fixtures &> ./logs/mink-test-server.log &

      - name: Run tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: 'max[total]=999999'
          BROWSER_NAME: ${{ matrix.browser }}
        run: |
          ./vendor/bin/simple-phpunit -v

      - name: Archive logs artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: logs_browser-${{ matrix.os }}-${{ matrix.browser }}_php-${{ matrix.php }}
          path: |
            logs
